version: '3.7'

services:
  nostr-relay:
    image: scsibug/nostr-rs-relay
    ports:
      - 7000:8080
    volumes: 
      - nostr-rs-relay-local-data:/usr/src/app/db
      - ./nostr-rs-relay/config.toml:/usr/src/app/config.toml
    user: root
    restart: always

volumes:
  nostr-rs-relay-local-data: