version: '3.7'

services:
  nostr-relay:
    image: scsibug/nostr-rs-relay:0.8.2
    ports:
      - 7000:8080
    volumes: 
      - ./nostr-rs-relay/data:/usr/src/app/db
      - ./nostr-rs-relay/config.toml:/usr/src/app/config.toml
    user: root
    container_name: nostr-reversi-relay